hugoblox:
  schema: "2.0"
  identity:
    name: Anna Coerver
    type: person
    tagline: Physics PhD Student at University of California, Berkeley
    description: ""
    organization: University of California, Berkeley
  theme:
    mode: light
    pack: default
    colors:
      primary: "#1E90FF"
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: md
    pack: modern
    families: {}
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: square
  header:
    title: 'Home'
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} Anna Coerver
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
